name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Existe archivo
      id: existe-archivo
      uses: education/autograding-command-grader@v1
      with:
        test-name: Existe archivo
        setup-command: ''
        command: go test -v ./00-mediciones/utiles/...
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        EXISTE-ARCHIVO_RESULTS: "${{steps.existe-archivo.outputs.result}}"
      with:
        runners: existe-archivo
